//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int quantity { get; set; }
        public int price_id { get; set; }
        public int type_id { get; set; }
        public string image_path { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public int state_id { get; set; }
    
        public virtual Price Price { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
